### ISSUE TITLE
Warnning: psi feats calculate failed ...

### ISSUE THREAD

**Issue by AIM132** [zchwang/IGModel#1]
Warnning: psi feats calculate failed ...
/home/Maderk/miniconda3/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(

你好，运行例子文件过后，报错如上，但是还是输出了Scores.csv，请问这样是否有影响，谢谢，部分环境如下
CUDA12.1
Pytorch2.1.0
dgl2.1.0

同时进行新的评估的时候，出现报错
python scripts/scoring.py -prefix ace -rec_fpath rec_1.pdb -ref_lig_fpath ligands.sdf -pose_fpath ace_decoys.mol2 -model models/saved_model.pth -out_fpath scores.csv
Traceback (most recent call last):
  File "scripts/scoring.py", line 125, in <module>
    rec.clip_rec()
  File "/home/Maderk/IGModel-master/scripts/load_receptor.py", line 197, in clip_rec
    self.clip_rec_ca_xyz_tensor = torch.cat(clip_ha_ca_xyz, axis=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
请问该如何解决

**Comment by zchwang** [comment]
The PSI angles are usually not computed for residues located at the protein chain terminus, so this warning does not affect the outcome. According to your error log, this error occurs during clipping protein. You should provide a co-crystal ligand structure (-ref_lig_fpath) to serve as a reference for clipping. 

Best regards!

**Comment by AIM132** [comment]
ok,thanks!

**Comment by AIM132** [comment]
> 通常不计算位于蛋白质链末端的残基的 PSI 角度，因此此警告不会影响结果。根据您的错误日志，此错误发生在剪裁蛋白质期间。您应该提供共晶配体结构 （-ref_lig_fpath） 作为削波的参考。
> 
> 此致敬意！

One more question, I downloaded the receptor protein PDB file from the PDB official website and only retained the ATOM part, as shown below. When executing the program as an input file for the receptor protein, an error was reported

eg :
ATOM      1  N   ASP A  40      35.784  72.211  67.437  1.00 47.96
ATOM      2  CA  ASP A  40      35.164  71.098  66.663  1.00 47.50
ATOM      3  C   ASP A  40      36.244  70.263  65.985  1.00 47.34
ATOM      4  O   ASP A  40      36.117  69.044  65.862  1.00 47.51
ATOM      5  CB  ASP A  40      34.179  71.647  65.630  1.00 99.99
ATOM      6  CG  ASP A  40      34.848  72.539  64.603  1.00 99.99
ATOM      7  OD1 ASP A  40      36.042  72.315  64.308  1.00 99.99
ATOM      8  OD2 ASP A  40      34.180  73.463  64.091  1.00 99.99
ATOM      9  N   GLU A  41      37.307  70.929  65.547  1.00 46.68
ATOM     10  CA  GLU A  41      38.419  70.260  64.882  1.00 46.09
ATOM     11  C   GLU A  41      39.223  69.474  65.916  1.00 45.81
ATOM     12  O   GLU A  41      39.862  68.466  65.594  1.00 45.67
ATOM     13  CB  GLU A  41      39.315  71.298  64.200  1.00 46.87
ATOM     14  CG  GLU A  41      40.370  70.727  63.262  1.00 47.65
ATOM     15  CD  GLU A  41      39.776  70.111  62.005  1.00 48.95
ATOM     16  OE1 GLU A  41      38.997  70.801  61.309  1.00 48.20
ATOM     17  OE2 GLU A  41      40.096  68.939  61.708  1.00 49.03

LWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(

receptor parsed ...
0
Error: 0
1
Error: 1
2
Error: 2
3
Error: 3
4
Error: 4
5
Error: 5
6

Is it an issue with the DGL version? Or does it mean that the PDB file needs to be processed? If I use the PDB file provided in the example, this problem will not occur.Thanks!

**Comment by zchwang** [comment]
This error is indeed difficult to pinpoint the cause. I suggest you modify `lines 77-78` of the /IGModel/scripts/scoring.py script as follows:
"
    except Exception as e:
        print("Error:", idx, e)
"
then rerun to check the error message

**Comment by AIM132** [comment]
> This error is indeed difficult to pinpoint the cause. I suggest you modify of the /IGModel/scripts/scoring.py script as follows: " except Exception as e: print("Error:", idx, e) " then rerun to check the error message`lines 77-78`

After modifying the code, an error is reported as follows

Error: 0 torch.cat(): expected a non-empty list of Tensors
1
Error: 1 torch.cat(): expected a non-empty list of Tensors
2
Error: 2 torch.cat(): expected a non-empty list of Tensors
3
Error: 3 torch.cat(): expected a non-empty list of Tensors
4
Error: 4 torch.cat(): expected a non-empty list of Tensors
5

**Comment by zchwang** [comment]
I suspect the error here might be due to your ligand poses being too far from the defined pocket (greater than 8 angstroms). You need to double-check whether these ligand poses are generated based on the pocket specified by `ref_lig_fpath`.

**Comment by AIM132** [comment]
ok thanks

**Comment by AIM132** [comment]
Perhaps the data I found for testing it was quite casual. I used decoys data before molecular docking, which explains why this error occurred. Thank you again
