### ISSUE TITLE
conda environment, problems with runing examples 

### ISSUE THREAD

**Issue by CLG68** [zchwang/IGModel#2]
Hi,

I created an environment that should contain everything needed to run your scripts:

conda create -n igmodel python=3.9
conda activate igmodel
conda install -c conda-forge cudatoolkit=11.8 rdkit numpy pandas openbabel spyrmsd lightning-utilities
pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 torchmetrics torchtext torchdata --index-url https://download.pytorch.org/whl/cu118
pip install torch-geometric pyyaml pydantic
pip install dgl -f https://data.dgl.ai/wheels/cu118/repo.html

I tested cuda support for torch, for DGL,... no problems importing them. so everything seems fine.  However, when I run: run_scoring.sh, I get:

(igmodel) christian@christian-linux01:/media/christian/VS/VS/Tool_IGModel$ ./run_scoring.sh
==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.

==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 2 that is
less than the observed explicit valence 3.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.

==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 2 that is
less than the observed explicit valence 3.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.

receptor clipped ...
/media/christian/VS/VS/Tool_IGModel/scripts/pocket_features.py:30: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:63.)
  n1 = torch.cross(b0, b1)
Warnning: psi feats calculate failed ...
/home/christian/anaconda3/envs/igmodel/lib/python3.9/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
receptor parsed ...
0
1
2
3
4
5
6
7
8
9

**Comment by zchwang** [comment]
This warning seems to be from OpenBabel and should not affect the scoring.

**Comment by CLG68** [comment]
Hi,

I also have torch/DGL warnings and "psi feats calculate failed ..." .  I'm not sure what are "psi feats" are.  There was no indication on the version of different packages for the environment on read.me page so I tried to install the latest stable DGL and limited the version of pytorch and Cuda to be compatible with it.  I installed the latest version of openbabel available on conda-forge.  as the one under pip is impossible to compile

I've got these results:

            | pred_rmsd | pred_pkd
1bcu-1 | 0.40509105 | 4.184812
1bcu-2 | 0.64704967 | 4.1000247
1bcu-3 | 2.626471 | 2.096566
1bcu-4 | 3.638276 | 1.0680594
1bcu-8 | 3.763526 | 1.7014754
1bcu-5 | 3.8416123 | 1.5569208
1bcu-6 | 4.9769936 | -0.40310478
1bcu-7 | 5.079344 | -0.46507454
1bcu-10 | 7.3024893 | -2.5734262
1bcu-9 | 7.5148563 | -2.7400494

**Comment by zchwang** [comment]
Hi, the PSI angles are usually not computed for residues located at the protein chain terminus, so this warning does not affect the outcome.

**Comment by CLG68** [comment]
Hi,

Do you get the same scores from this set?  If everything seems to be ok, I'll find a way to suppress the warnings.

Thanks again for your help,
Christian

**Comment by CLG68** [comment]
Hi,
Maybe you could add the 2 attached files.  With conda env -f environment.yml, they will create a functional environment named igmodel.  Just rename environment.txt to environment.yml as Github did not let me attach a yml file.
[environment.txt](https://github.com/zchwang/IGModel/files/15206592/environment.txt)
[requirements.txt](https://github.com/zchwang/IGModel/files/15206593/requirements.txt)
 Best,
 Christian
