### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by CLG68** [zchwang/IGModel#3]
Hi,

I would like to make a suggestion:

instead of using a prefix and a number for each pose, it would be more practical for a screen to use the name of that pose as defined in the sd file.  If not, we need for each file to create a list of names, extract the scores from the result file and merge them into a new file.

Furthermore, when IGModel does not like one pose, it just skip, so it does not generate a line with an empty score.  So if I process 1000 poses, I could end up with 998 lines if 2 poses were skipped.  Fortunately, there is a way to trace which one was skipped as the numbering will show it.  To resynchronize the list of names with the scores, I'll need a script to insert the missing lines before merging with the names-list.

An other problem related to merging the name list with the scores is that IGModel will force a prefix and then sort by score so it desynchronizes the 2 lists; as the first column has a prefix, the content is not numeric, you cannot just sort it as for ex: cmpd-11 will be seen as smaller than cmpd-2. If we could have the possibility of not having a prefix, just the numbers, it would be easier.  It is not a big deal to compensate with a script and remove the prefix before sorting, however, even small corrections could waste a lot of time and unnecessary disk operations, at the end, when millions of poses are processed.

best

**Comment by zchwang** [comment]
Hi, I'm sorry for the late reply. 
Thank you very much for your suggestion. I will soon make further adjustments to the script to make it more user-friendly.

**Comment by CLG68** [comment]
Thank you; it is a very useful tool.  These are just suggestions as I was able to compensate for all of these using a script so I can already use it.  It is just that my solutions are creating more disk activity than needed and over millions of files it could add up.
Best,
Christian
